; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool on Thu Nov 16 2017 18:16:14 GMT-0600 (Central Standard Time)


; Move quickly to z axis endstop and stop there (first pass)

; Lift Z relatively to current position
G91;
G1 S2 Z5 ;

; Move Z up until the switch triggers
G1 Z210 V210 S1 F1800;

; Go back a few mm
G91;
G1 S2 Z-5; 
G90

; Move slowly to Z axis endstop once more (second pass)
G1 S1 Z605 V605 F360;

G91;
G1 S2 Z-5; 
G90;


; Back to absolute positioning
G90

