; homeall.g
; called to home all axes
;
; generated by RepRapFirmware Configuration Tool on Thu Nov 16 2017 18:16:14 GMT-0600 (Central Standard Time)

; Relative positioning
G91

; Lift Z
G1 S2 Z5 F6000

; Course home X and Y
M584 X0 U3 ; Split X into 2 (X+U)
G1 X-605 U-605 Y327 F1800 S1

; Move away from the endstops
G1 X5 U5 Y-5 F600

; Fine home X and Y
G1 X-605 U-605 Y327 F360 S1

M584 X0:3     ; Join U to X again

; Move quickly to X axis endstop and stop there (first pass)


; Move Z up until the switch triggers
G1 Z210 S1 F1800;

; Go back a few mm
G91;
G1 S2 Z-5; 
G90;

; Move slowly to Z axis endstop once more (second pass)
G1 S1 Z605 F360;

G91;
G1 S2 Z-5; 
G90;

; Back to absolute positioning
G90;


