; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool on Thu Nov 16 2017 18:16:14 GMT-0600 (Central Standard Time)

; Lift Z relative to current position
G91
G1 S2 Z5 F2000
G90

; Move quickly to X axis endstop and stop there (first pass)
M584 X0 U3 ; Split X into 2 (X+U)
G1 S1 X-605 U-605 F1500

; Go back a few mm
G91
G1 S2 X5 U5 
G90

; Move slowly to X axis endstop once more (second pass)
G1 S1 X-605 U-605 F360

M584 X0:3     ; Join U to X again

; Go back a few mm
G91
G1 S2 X5 U5 
G90

; Lower Z again
G91
G1 S2 Z-5 F2000
G90
;;;;

