; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool on Thu Nov 16 2017 18:16:14 GMT-0600 (Central Standard Time)

; Lift Z relative to current position
G91
G1 S2 Z5 F6000
G90

; Move quickly to Y axis endstop and stop there (first pass)
G1 Y327 F1800 S1

; Go back a few mm
G91
G1 Y-5 F6000
G90

; Move slowly to X axis endstop once more (second pass)
G1 Y327 F360 S1

; Lower Z again
G91
G1 S2 Z-5 F6000
G90
;;;


